# Analysis parameters
analysis:
  num_sentences: 10
  temperature: 1.0
  use_sampling: true
  control:
    enabled: true  # This is the only flag we need for control
    # Default control settings with increased magnitude
    layer_weights:
      - 1.0  # Layer 1
      - 1.2  # Layer 2
      - 1.4  # Layer 3
      - 1.6  # Layer 4
      - 1.8  # Layer 5
      - 2.0  # Layer 6
      - 2.0  # Layer 7
      - 1.8  # Layer 8
      - 1.6  # Layer 9
      - 1.4  # Layer 10
      - 1.2  # Layer 11
      - 1.0  # Layer 12
    token_weights:
      - 1.0  # Start token
      - 1.5
      - 2.0
      - 2.5
      - 3.0  # End token
    control_vectors:
      # Strong control vectors with significant impact
      positive:
        - 2.0   # Stronger direct influence
        - 2.5
        - 3.0
        - 3.5
        - 4.0   # Maximum direct influence
      negative:
        - -2.0  # Stronger direct influence
        - -2.5
        - -3.0
        - -3.5
        - -4.0  # Maximum direct influence
