# Analysis parameters
analysis:
  num_sentences: 10
  temperature: 1.0
  use_sampling: false
  control:
    enabled: false
    layer_weights: null  # Set to array of weights per layer if needed
    token_weights: null  # Set to array of weights per token if needed

# Model parameters
models:
  gpt2:
    name: "gpt2"
    output_hidden_states: true
  bert:
    name: "google-bert/bert-base-uncased"
    output_hidden_states: true

# Output paths
output:
  plots_dir: "plots"
  results_dir: "results"
